# Generated by Django 5.2.7 on 2025-10-28 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.IntegerField(default=0)),
                ('date_consumed', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ['-date_consumed', '-id'],
            },
        ),
    ]
